name: gradle build and upload cocoapod

on: [push]

jobs:
  test-swift:
    name: Test Swift project
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute test
        run: |
          cd kotlin-library-test
          pod install
          xcodebuild -workspace kotlin-library-test.xcworkspace -scheme kotlin-library-swift-test -arch 'x86_64' test

#jobs:
#  build:
#    name: Create Release
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Fifth automated release
#          draft: false
#          prerelease: true

#jobs:
#  tag:
#    runs-on: macOS-latest
#    steps:
#      - name: Create tag
#        uses: actions/github-script@v5
#        with:
#          script: |
#            github.rest.git.createRef({
#              owner: context.repo.owner,
#             repo: context.repo.repo,
#              ref: 'refs/tags/0.1.4',
#              sha: context.sha
#            })

#jobs:
#  build: 
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 15
#      uses: actions/setup-java@v2
#      with:
#        java-version: '15'
#        distribution: 'adopt'
#    - name: Validate Gradle wrapper
#      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#    - name: Build with Gradle
#      run: |
#        ./gradlew --no-daemon linkReleaseFrameworkIosX64
#        git config --global user.name 'SpiderSwift'
#        git config --global user.email 'artem.pishchalov@gmail.com'
#        git add --all
#        git commit -m "Automated build push"
#        git push

#  upload:
#    runs-on: macOS-latest
 #   needs: build
#    steps:
#    - uses: actions/checkout@v1
#    - name: Publish to CocoaPod register
#      env:
#        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
#      run: |
#        pod trunk push kotlin_library.podspec
