name: gradle build and upload cocoapod

on: [push]

jobs:
  build: 
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      run: ./gradlew --no-daemon linkReleaseFrameworkIosX64
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Commit report
        run: |
          git config --global user.name 'SpiderSwift'
          git config --global user.email 'artem.pishchalov@gmail.com'
          git commit -am "Automated build push"
          git push

#  upload:
#    runs-on: macOS-latest
 #   needs: build
#    steps:
#    - uses: actions/checkout@v1
#    - name: Publish to CocoaPod register
#      env:
#        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
#      run: |
#        pod trunk push kotlin_library.podspec
